Models/CuisineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Models
{
    public enum CuisineType
    {
        None,
        French,
        Italian,
        German
    }
}

Models/Restaurant.cs
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }

        [Display(Name = "Restaurant Name")]
        public string Name { get; set; }

        public CuisineType Cuisine { get; set; }
    }  
}

ViewModels/IndexViewModel.cs
using System.Collections.Generic;
using OdeToFood.Models;

namespace OdeToFood.ViewModels
{
    public class IndexViewModel
    {
        public IEnumerable<Restaurant> Restaurants { get; set;}
        public string MessageOfTheDay { get; set; }
    }
}

ViewModels/RestaurantEditModel.cs
using OdeToFood.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MinLength(3)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Models;
using OdeToFood.Services;
using OdeToFood.ViewModels;

namespace OdeToFood.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRestaurantData _restaurantData;
        private readonly IGreetService _greetService;

        public HomeController(IRestaurantData restaurantData, IGreetService greetService)
        {
            this._restaurantData = restaurantData;
            this._greetService = greetService;
        }

        public IActionResult Index()
        {
            var model = new IndexViewModel
            {
                Restaurants = _restaurantData.GetAll(),
                MessageOfTheDay = _greetService.GetMessageOfTheDay()
            };

            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _restaurantData.Get(id);

            if (model == null)
                return NotFound();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RestaurantEditModel model)
        {
            if (ModelState.IsValid)
            {
                var restaurant = new Restaurant
                {
                    Name = model.Name,
                    Cuisine = model.Cuisine
                };

                var newRestaurant = _restaurantData.Add(restaurant);

                return RedirectToAction("Details", new { Id = newRestaurant.Id });
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    // represents the @model for the Razor page for
    // which this is the code behind file
    public class GreetingModel : PageModel
    {
        private IGreetService _greetService;

        public string CurrentGreeting { get; set; }

        public GreetingModel(IGreetService greetService)
        {
            _greetService = greetService;
        }
        public void OnGet(string name)
        {
            CurrentGreeting = $"{name} says: {_greetService.GetMessageOfTheDay()} - from Razor Code behind!";
        }
    }
}

Pages/Restaurants/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Models;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        private IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }

        public EditModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public IActionResult OnGet(int id)
        {
            Restaurant = _restaurantData.Get(id);

            if (Restaurant == null)
            {
                // note that we have access to these Controller-View based helpers
                return RedirectToAction("Index", "Home");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _restaurantData.Update(Restaurant);
                return RedirectToAction("Details", "Home", new { id = Restaurant.Id });
            }

            // will use "asp-validation-for" tag helpers to set error messages on failed model properties
            return Page();
        }
    }
}

ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreetService _greetService;

        public GreeterViewComponent(IGreetService greetService)
        {
            _greetService = greetService;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greetService.GetMessageOfTheDay();

            return View("Default", model);
        }
    }
}

Pages/Greeting.cshtml
@page "{name?}"

@model GreetingModel

<div>@Model.CurrentGreeting</div>

@section footer {
    "Footer from Greeting Razor Page!"
}

Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Restaurants

@model EditModel

<h1>Edit @Model.Restaurant</h1>
<form method="post">
    <input type="hidden" asp-for="@Model.Restaurant.Id" />
    <div>
        <label asp-for="@Model.Restaurant.Name"></label>
        <input asp-for="@Model.Restaurant.Name">
        <span asp-validation-for="@Model.Restaurant.Name"></span>
    </div>

    <div>
        <label asp-for="@Model.Restaurant.Cuisine"></label>
        <select asp-for="@Model.Restaurant.Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="@Model.Restaurant.Cuisine"></span>
    </div>

    <input type="submit" name="save" value="Save" />
</form>

Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>@RenderSection("footer", required: false)</footer>
</body>
</html>

Views/Home/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Restaurant

@{
    ViewBag.Title = "Create";
}

<h1>Add Restaurant</h1>
<form method="post">
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name">
        <span asp-validation-for="Name"></span>
    </div>

    <div>
        <label asp-for="Cuisine"></label>
        <select asp-for="Cuisine"
                asp-items="@Html.GetEnumSelectList<CuisineType>()"></select>
        <span asp-validation-for="Cuisine"></span>
    </div>

    <input type="submit" name="save" value="Save" />
</form>

Views/Home/Details.cshtml
@model Restaurant

@{
    ViewBag.Title = "Details";
}

<h1>@Model.Name</h1>

<div>Id: @Model.Id</div>
<div>Cuisine: @Model.Cuisine</div>

<a asp-action="Index">Home</a>

Views/Home/Index.cshtml
@model IndexViewModel

@{ 
    ViewBag.Title = "Index Page";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>All Restaurants</h1>

@foreach(var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant)
}

<div>
    <a asp-action="Create">Add Restaurants</a>
</div>

@section footer {
    @Model.MessageOfTheDay
}

Views/Home/_Summary.cshtml
@model  Restaurant

<section>
    <h3>@Model.Name</h3>
    <div>
        Cuisine: @Model.Cuisine
    </div>
    <div>
        <a href="home/details/@Model.Id">Details (Anchor tag)</a>
        @Html.ActionLink("Go (Html.ActionLink)", "Details", new { Id = @Model.Id })
        <a asp-action="Details" asp-route-id="@Model.Id">More (tag helper)</a>
        <a asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit (Razor Page)</a>
    </div>
</section>

Views/Shared/Components/Greeter/Default.cshtml
@model string

<h6>Quote of the day: @Model</h6>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required: false)
        <vc:greeter></vc:greeter>
    </footer>
</body>
</html>